name: Notebook examples zip archive

on:
  workflow_call:

permissions:
  contents: read

jobs:
  examples-artifact:

    strategy:
      matrix:
        os: [ubuntu-latest]
        python: ["3.11"]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install tooling
        run: |
          python -m pip install --upgrade pip
      - name: Install dependencies
        run: |
          python -m pip install jupyter-client~=8.6 jupytext~=1.16
      - name: Convert notebooks
        run: |
          python -m jupytext --opt notebook_metadata_filter=-kernelspec \
            --to ipynb docs/source/examples/*.md
      - name: Archive notebook and data artifact
        uses: actions/upload-artifact@v4
        with:
          name: notebook-examples
          path: |
            docs/source/examples/*.ipynb
            docs/source/examples/data
