# Regular QA workflow for main branch

name: Test

on:
  push:
    branches:
      - main

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    needs: [code-quality]
  notebook-examples:
    uses: ./.github/workflows/notebook-examples.yml
    needs: [code-quality]
  examples-artifact:
    uses: ./.github/workflows/examples-artifact.yml
    needs: [code-quality]
  trigger-rtd-build:
    runs-on: ubuntu-latest
    # Job must be completed by the time RTD sees it
    needs: [code-quality,unit-tests,notebook-examples,examples-artifact]
    steps:
      - name: Trigger RTD build
        env:
          RTD_HOOK_TOKEN: ${{ secrets.RTD_HOOK_TOKEN }}
        run: |
          curl -X POST -d "branches=main" -d "token=$RTD_HOOK_TOKEN" \
            -d "default_branch=main" \
            https://readthedocs.com/api/v2/webhook/gurobi-optimization-gurobipy-pandas/11030/
