# QA workflow for pull requests (no RTD trigger)
#
# Using pull_request here. Ideally would use pull_request_target but that
# requires some reworking of the callable workflows to make sure the right
# commit is checked out in each case (TODO).

name: Pull request

on:
  pull_request:
    branches:
      - main

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    needs: [code-quality]
  notebook-examples:
    uses: ./.github/workflows/notebook-examples.yml
    needs: [unit-tests]
  examples-artifact:
    uses: ./.github/workflows/examples-artifact.yml
    needs: [notebook-examples]
