# Build and upload a wheel. No tests run, this should be
# handled via a larger workflow

name: Publish to PyPI

on:
  workflow_call:

jobs:
  publish-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Install twine uploader
        run: |
          python -m pip install --upgrade pip
          python -m pip install twine
      - name: Fetch wheel artifact
        uses: actions/download-artifact@v3
        with:
          name: wheel-artifact
          path: dist
      - name: Fetch sdist artifact
        uses: actions/download-artifact@v3
        with:
          name: sdist-artifact
          path: dist
      - name: File listing
        run: ls -R
      - name: Publish with twine
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: twine upload -u __token__ -p $PYPI_TOKEN dist/*
