# Regular QA workflow (pull requests, main branch)

name: Test

on:
  push:
    branches:
      - main
  pull_request_target:
    branches:
      - main

jobs:
  code-quality:
    uses: ./.github/workflows/code-quality.yml
  unit-tests:
    uses: ./.github/workflows/unit-tests.yml
    needs: [code-quality]
  notebook-examples:
    uses: ./.github/workflows/notebook-examples.yml
    needs: [unit-tests]
